/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  StrengthsFinder: [
    {
      type: 'category',
      label: '优势分析',
      items: [
        'strengths-finder/finding',
        'strengths-finder/applying',
        // 'strengths-finder/cliftonStrengths-themes',
      ],
    },
    'the-one-thing',
    {
      type: 'category',
      label: '逆向工作（亚马逊）',
      items: [
        'working-backwards/intro',
        'working-backwards/buliding-blocks',
        'working-backwards/hiring',
        'working-backwards/organizing',
        'working-backwards/communicating',
      ],
    },
    {
      type: 'category',
      label: 'LeetCode',
      items: [
        'data-structures-algorithms/categories/index',
        'data-structures-algorithms/base',
        'data-structures-algorithms/complexity',
        {
          type: 'category',
          label: '算法专题 (Draft)',
          items: [
            'data-structures-algorithms/categories/array',
            'data-structures-algorithms/categories/string',
            'data-structures-algorithms/categories/two-pointers',
            'data-structures-algorithms/categories/linked-list',
            'data-structures-algorithms/categories/tree',
            'data-structures-algorithms/categories/dynamic-programming',

            'data-structures-algorithms/categories/backtracking',
            'data-structures-algorithms/categories/depth-first-search',
            'data-structures-algorithms/categories/breadth-first-search',
            'data-structures-algorithms/categories/binary-search',
            'data-structures-algorithms/categories/hash-table',
            'data-structures-algorithms/categories/sorting',
            'data-structures-algorithms/categories/bit-manipulation',
            'data-structures-algorithms/categories/union-find',

            'data-structures-algorithms/categories/sliding-window',
            'data-structures-algorithms/categories/segment-tree',
            'data-structures-algorithms/categories/binary-indexed-tree',

          ],
        },
        'data-structures-algorithms/fibonacci',

      ],
    },
    {
      type: 'category',
      label: 'Swift',
      items: [
        'swift/explore'
      ],
      
    }
  ],

  Methodology: [{
    type: 'category',
    label: '沉淀方法论',
    items: [
      'methodology/intro',
      'methodology/performance',
      'methodology/resume-identify',
      'underlying-logic/subject-separation',
    ],
  }]


};

module.exports = sidebars;
